
services:
  postgres:
    container_name: postgres_container_for_eventify
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app_network
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

volumes:
    postgres:

networks:
  app_network:
    driver: bridge

