auth:
  port: 9091
  secret-key: "VxCDGAeugvEa6jvBiFYcOboddRGKydns"

event:
  port: 9092

user-interact:
  port: 9093

notification:
  port: 9095

postgres:
  host: "postgres"
  port: 5432
  username: "eventify-user"
  password: "eventify-password"
  database: "eventify"

kafka:
  host: kafka
  port: 9094
  brokers:
    - "kafka:9094"
