syntax = "proto3";

package userinteract.v1;

option go_package = "eventify/user-interaction/api;uipb";

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "User-Interact Service API"
    version: "1.0"
    description: "User Interaction service for users"
  };
  host: "localhost/api";
  schemes: HTTP;
  consumes: "application/json";
  produces: "application/json";
};


service UserInteractionService {
  // Reviews
  rpc CreateReview (CreateReviewRequest) returns (CreateReviewResponse) {
    option (google.api.http) = {
      post: "/user-interact"
      body: "*"
    };
  }

  rpc ListReviewsByEvent (ListReviewsByEventRequest) returns (ListReviewsByEventResponse) {
    option (google.api.http) = {
      get: "/user-interact/event/{event_id}"
    };
  }

  rpc UpdateReview (UpdateReviewRequest) returns (UpdateReviewResponse) {
    option (google.api.http) = {
      put: "/user-interact/{review_id}"
      body: "*"
    };
  }

  rpc DeleteReview (DeleteReviewRequest) returns (DeleteReviewResponse) {
    option (google.api.http) = {
      delete: "/user-interact/{review_id}"
    };
  }

  // Registrations
  rpc RegisterForEvent (RegisterForEventRequest) returns (RegisterForEventResponse) {
    option (google.api.http) = {
      post: "/registration/event/{event_id}"
      body: "*"
    };
  }

  rpc DeleteRegistration (DeleteRegistrationRequest) returns (DeleteRegistrationResponse) {
    option (google.api.http) = {
      delete: "/registration/event/{event_id}"
    };
  }

  rpc ListRegistrations (ListRegistrationsRequest) returns (ListRegistrationsResponse) {
    option (google.api.http) = {
      get: "/registration/event/{event_id}"
    };
  }
}

// Reviews
message CreateReviewRequest {
  uint64 event_id = 1 [(validate.rules).uint64 = {gt: 0}];
  uint64 user_id = 2 [(validate.rules).uint64 = {gt: 0}];
  string username = 3 [(validate.rules).string = {
    min_len:3,
    max_len: 32,
    pattern: "^[a-zA-Z0-9_]+$"
  }];
  uint32 rating = 4 [(validate.rules).uint32 = {gte: 1, lte: 5}];
  string comment = 5 [(validate.rules).string = {min_len: 1, max_len: 500}];
}

message CreateReviewResponse { string message = 1; }

message ListReviewsByEventRequest {
  uint64 event_id = 1 [(validate.rules).uint64 = {gt: 0}];
}
message ListReviewsByEventResponse {
  repeated Review reviews = 1 [(validate.rules).repeated = {min_items: 0, max_items: 100}];
}

message UpdateReviewRequest {
  uint64 review_id = 1 [(validate.rules).uint64 = {gt: 0}];
  uint32 rating = 2 [(validate.rules).uint32 = {gte: 1, lte: 5}];
  string comment = 3 [(validate.rules).string = {min_len: 1, max_len: 500}];
  uint64 user_id = 4 [(validate.rules).uint64 = {gt: 0}];
  string username = 5 [(validate.rules).string = {min_len: 3, max_len: 32}];
  uint64 event_id = 6 [(validate.rules).uint64 = {gt: 0}];
}

message UpdateReviewResponse { string message = 1; }

message DeleteReviewRequest {
  uint64 review_id = 1 [(validate.rules).uint64 = {gt: 0}];
}

message DeleteReviewResponse { string message = 1; }

message Review {
  uint64 id = 1 [(validate.rules).uint64 = {gt: 0}];
  uint64 event_id = 2 [(validate.rules).uint64 = {gt: 0}];
  uint64 user_id = 3 [(validate.rules).uint64 = {gt: 0}];
  string username = 4 [(validate.rules).string = {min_len: 3, max_len: 32}];
  uint32 rating = 5 [(validate.rules).uint32 = {gte: 1, lte: 5}];
  string comment = 6 [(validate.rules).string = {min_len: 1, max_len: 500}];
  string created_at = 7 [(validate.rules).string = {pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$"}];
  string updated_at = 8 [(validate.rules).string = {pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$", ignore_empty: true}];
}

// Registrations

message RegisterForEventRequest {
  uint64 event_id = 1 [(validate.rules).uint64 = {gt: 0}];
  uint64 user_id = 2 [(validate.rules).uint64 = {gt: 0}];
  string username = 3 [(validate.rules).string = {min_len: 3, max_len: 32}];
}

message RegisterForEventResponse { string message = 1; }

message DeleteRegistrationRequest {
  uint64 event_id = 1 [(validate.rules).uint64 = {gt: 0}];
  uint64 user_id = 2 [(validate.rules).uint64 = {gt: 0}];
}

message DeleteRegistrationResponse { string message = 1; }

message ListRegistrationsRequest {
  uint64 event_id = 1 [(validate.rules).uint64 = {gt: 0}];
}

message ListRegistrationsResponse {
  repeated Participant participants = 1 [(validate.rules).repeated = {min_items: 0, max_items: 100}];
}

message Participant {
  uint64 id = 1 [(validate.rules).uint64 = {gt: 0}];
  string username = 2 [(validate.rules).string = {min_len: 3, max_len: 32}];
}