// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user-interact.proto

package uipb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReviewRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReviewRequestMultiError, or nil if none found.
func (m *CreateReviewRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReviewRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := CreateReviewRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := CreateReviewRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := CreateReviewRequestValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateReviewRequest_Username_Pattern.MatchString(m.GetUsername()) {
		err := CreateReviewRequestValidationError{
			field:  "Username",
			reason: "value does not match regex pattern \"^[a-zA-Z0-9_]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetRating(); val < 1 || val > 5 {
		err := CreateReviewRequestValidationError{
			field:  "Rating",
			reason: "value must be inside range [1, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetComment()); l < 1 || l > 500 {
		err := CreateReviewRequestValidationError{
			field:  "Comment",
			reason: "value length must be between 1 and 500 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateReviewRequestMultiError(errors)
	}

	return nil
}

// CreateReviewRequestMultiError is an error wrapping multiple validation
// errors returned by CreateReviewRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateReviewRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReviewRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReviewRequestMultiError) AllErrors() []error { return m }

// CreateReviewRequestValidationError is the validation error returned by
// CreateReviewRequest.Validate if the designated constraints aren't met.
type CreateReviewRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReviewRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReviewRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReviewRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReviewRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReviewRequestValidationError) ErrorName() string {
	return "CreateReviewRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReviewRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReviewRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReviewRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReviewRequestValidationError{}

var _CreateReviewRequest_Username_Pattern = regexp.MustCompile("^[a-zA-Z0-9_]+$")

// Validate checks the field values on CreateReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReviewResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReviewResponseMultiError, or nil if none found.
func (m *CreateReviewResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReviewResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return CreateReviewResponseMultiError(errors)
	}

	return nil
}

// CreateReviewResponseMultiError is an error wrapping multiple validation
// errors returned by CreateReviewResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateReviewResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReviewResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReviewResponseMultiError) AllErrors() []error { return m }

// CreateReviewResponseValidationError is the validation error returned by
// CreateReviewResponse.Validate if the designated constraints aren't met.
type CreateReviewResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReviewResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReviewResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReviewResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReviewResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReviewResponseValidationError) ErrorName() string {
	return "CreateReviewResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReviewResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReviewResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReviewResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReviewResponseValidationError{}

// Validate checks the field values on ListReviewsByEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListReviewsByEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReviewsByEventRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReviewsByEventRequestMultiError, or nil if none found.
func (m *ListReviewsByEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReviewsByEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := ListReviewsByEventRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListReviewsByEventRequestMultiError(errors)
	}

	return nil
}

// ListReviewsByEventRequestMultiError is an error wrapping multiple validation
// errors returned by ListReviewsByEventRequest.ValidateAll() if the
// designated constraints aren't met.
type ListReviewsByEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReviewsByEventRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReviewsByEventRequestMultiError) AllErrors() []error { return m }

// ListReviewsByEventRequestValidationError is the validation error returned by
// ListReviewsByEventRequest.Validate if the designated constraints aren't met.
type ListReviewsByEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReviewsByEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReviewsByEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReviewsByEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReviewsByEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReviewsByEventRequestValidationError) ErrorName() string {
	return "ListReviewsByEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListReviewsByEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReviewsByEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReviewsByEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReviewsByEventRequestValidationError{}

// Validate checks the field values on ListReviewsByEventResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListReviewsByEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReviewsByEventResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReviewsByEventResponseMultiError, or nil if none found.
func (m *ListReviewsByEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReviewsByEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetReviews()) > 100 {
		err := ListReviewsByEventResponseValidationError{
			field:  "Reviews",
			reason: "value must contain no more than 100 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetReviews() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListReviewsByEventResponseValidationError{
						field:  fmt.Sprintf("Reviews[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListReviewsByEventResponseValidationError{
						field:  fmt.Sprintf("Reviews[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReviewsByEventResponseValidationError{
					field:  fmt.Sprintf("Reviews[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListReviewsByEventResponseMultiError(errors)
	}

	return nil
}

// ListReviewsByEventResponseMultiError is an error wrapping multiple
// validation errors returned by ListReviewsByEventResponse.ValidateAll() if
// the designated constraints aren't met.
type ListReviewsByEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReviewsByEventResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReviewsByEventResponseMultiError) AllErrors() []error { return m }

// ListReviewsByEventResponseValidationError is the validation error returned
// by ListReviewsByEventResponse.Validate if the designated constraints aren't met.
type ListReviewsByEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReviewsByEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReviewsByEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReviewsByEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReviewsByEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReviewsByEventResponseValidationError) ErrorName() string {
	return "ListReviewsByEventResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListReviewsByEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReviewsByEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReviewsByEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReviewsByEventResponseValidationError{}

// Validate checks the field values on UpdateReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateReviewRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateReviewRequestMultiError, or nil if none found.
func (m *UpdateReviewRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateReviewRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetReviewId() <= 0 {
		err := UpdateReviewRequestValidationError{
			field:  "ReviewId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetRating(); val < 1 || val > 5 {
		err := UpdateReviewRequestValidationError{
			field:  "Rating",
			reason: "value must be inside range [1, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetComment()); l < 1 || l > 500 {
		err := UpdateReviewRequestValidationError{
			field:  "Comment",
			reason: "value length must be between 1 and 500 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := UpdateReviewRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := UpdateReviewRequestValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetEventId() <= 0 {
		err := UpdateReviewRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateReviewRequestMultiError(errors)
	}

	return nil
}

// UpdateReviewRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateReviewRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateReviewRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateReviewRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateReviewRequestMultiError) AllErrors() []error { return m }

// UpdateReviewRequestValidationError is the validation error returned by
// UpdateReviewRequest.Validate if the designated constraints aren't met.
type UpdateReviewRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateReviewRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateReviewRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateReviewRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateReviewRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateReviewRequestValidationError) ErrorName() string {
	return "UpdateReviewRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateReviewRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateReviewRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateReviewRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateReviewRequestValidationError{}

// Validate checks the field values on UpdateReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateReviewResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateReviewResponseMultiError, or nil if none found.
func (m *UpdateReviewResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateReviewResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return UpdateReviewResponseMultiError(errors)
	}

	return nil
}

// UpdateReviewResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateReviewResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateReviewResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateReviewResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateReviewResponseMultiError) AllErrors() []error { return m }

// UpdateReviewResponseValidationError is the validation error returned by
// UpdateReviewResponse.Validate if the designated constraints aren't met.
type UpdateReviewResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateReviewResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateReviewResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateReviewResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateReviewResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateReviewResponseValidationError) ErrorName() string {
	return "UpdateReviewResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateReviewResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateReviewResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateReviewResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateReviewResponseValidationError{}

// Validate checks the field values on DeleteReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteReviewRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteReviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteReviewRequestMultiError, or nil if none found.
func (m *DeleteReviewRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteReviewRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetReviewId() <= 0 {
		err := DeleteReviewRequestValidationError{
			field:  "ReviewId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteReviewRequestMultiError(errors)
	}

	return nil
}

// DeleteReviewRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteReviewRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteReviewRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteReviewRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteReviewRequestMultiError) AllErrors() []error { return m }

// DeleteReviewRequestValidationError is the validation error returned by
// DeleteReviewRequest.Validate if the designated constraints aren't met.
type DeleteReviewRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteReviewRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteReviewRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteReviewRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteReviewRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteReviewRequestValidationError) ErrorName() string {
	return "DeleteReviewRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteReviewRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteReviewRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteReviewRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteReviewRequestValidationError{}

// Validate checks the field values on DeleteReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteReviewResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteReviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteReviewResponseMultiError, or nil if none found.
func (m *DeleteReviewResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteReviewResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return DeleteReviewResponseMultiError(errors)
	}

	return nil
}

// DeleteReviewResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteReviewResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteReviewResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteReviewResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteReviewResponseMultiError) AllErrors() []error { return m }

// DeleteReviewResponseValidationError is the validation error returned by
// DeleteReviewResponse.Validate if the designated constraints aren't met.
type DeleteReviewResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteReviewResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteReviewResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteReviewResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteReviewResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteReviewResponseValidationError) ErrorName() string {
	return "DeleteReviewResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteReviewResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteReviewResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteReviewResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteReviewResponseValidationError{}

// Validate checks the field values on Review with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Review) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Review with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ReviewMultiError, or nil if none found.
func (m *Review) ValidateAll() error {
	return m.validate(true)
}

func (m *Review) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ReviewValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetEventId() <= 0 {
		err := ReviewValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := ReviewValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := ReviewValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetRating(); val < 1 || val > 5 {
		err := ReviewValidationError{
			field:  "Rating",
			reason: "value must be inside range [1, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetComment()); l < 1 || l > 500 {
		err := ReviewValidationError{
			field:  "Comment",
			reason: "value length must be between 1 and 500 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_Review_CreatedAt_Pattern.MatchString(m.GetCreatedAt()) {
		err := ReviewValidationError{
			field:  "CreatedAt",
			reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}Z$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUpdatedAt() != "" {

		if !_Review_UpdatedAt_Pattern.MatchString(m.GetUpdatedAt()) {
			err := ReviewValidationError{
				field:  "UpdatedAt",
				reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}Z$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ReviewMultiError(errors)
	}

	return nil
}

// ReviewMultiError is an error wrapping multiple validation errors returned by
// Review.ValidateAll() if the designated constraints aren't met.
type ReviewMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReviewMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReviewMultiError) AllErrors() []error { return m }

// ReviewValidationError is the validation error returned by Review.Validate if
// the designated constraints aren't met.
type ReviewValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReviewValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReviewValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReviewValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReviewValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReviewValidationError) ErrorName() string { return "ReviewValidationError" }

// Error satisfies the builtin error interface
func (e ReviewValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReview.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReviewValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReviewValidationError{}

var _Review_CreatedAt_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$")

var _Review_UpdatedAt_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$")

// Validate checks the field values on RegisterForEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterForEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterForEventRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterForEventRequestMultiError, or nil if none found.
func (m *RegisterForEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterForEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := RegisterForEventRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := RegisterForEventRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := RegisterForEventRequestValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegisterForEventRequestMultiError(errors)
	}

	return nil
}

// RegisterForEventRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterForEventRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterForEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterForEventRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterForEventRequestMultiError) AllErrors() []error { return m }

// RegisterForEventRequestValidationError is the validation error returned by
// RegisterForEventRequest.Validate if the designated constraints aren't met.
type RegisterForEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterForEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterForEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterForEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterForEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterForEventRequestValidationError) ErrorName() string {
	return "RegisterForEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterForEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterForEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterForEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterForEventRequestValidationError{}

// Validate checks the field values on RegisterForEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterForEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterForEventResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterForEventResponseMultiError, or nil if none found.
func (m *RegisterForEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterForEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return RegisterForEventResponseMultiError(errors)
	}

	return nil
}

// RegisterForEventResponseMultiError is an error wrapping multiple validation
// errors returned by RegisterForEventResponse.ValidateAll() if the designated
// constraints aren't met.
type RegisterForEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterForEventResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterForEventResponseMultiError) AllErrors() []error { return m }

// RegisterForEventResponseValidationError is the validation error returned by
// RegisterForEventResponse.Validate if the designated constraints aren't met.
type RegisterForEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterForEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterForEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterForEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterForEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterForEventResponseValidationError) ErrorName() string {
	return "RegisterForEventResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterForEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterForEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterForEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterForEventResponseValidationError{}

// Validate checks the field values on DeleteRegistrationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRegistrationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRegistrationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRegistrationRequestMultiError, or nil if none found.
func (m *DeleteRegistrationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRegistrationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := DeleteRegistrationRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := DeleteRegistrationRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteRegistrationRequestMultiError(errors)
	}

	return nil
}

// DeleteRegistrationRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteRegistrationRequest.ValidateAll() if the
// designated constraints aren't met.
type DeleteRegistrationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRegistrationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRegistrationRequestMultiError) AllErrors() []error { return m }

// DeleteRegistrationRequestValidationError is the validation error returned by
// DeleteRegistrationRequest.Validate if the designated constraints aren't met.
type DeleteRegistrationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRegistrationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRegistrationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRegistrationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRegistrationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRegistrationRequestValidationError) ErrorName() string {
	return "DeleteRegistrationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRegistrationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRegistrationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRegistrationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRegistrationRequestValidationError{}

// Validate checks the field values on DeleteRegistrationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRegistrationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRegistrationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRegistrationResponseMultiError, or nil if none found.
func (m *DeleteRegistrationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRegistrationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return DeleteRegistrationResponseMultiError(errors)
	}

	return nil
}

// DeleteRegistrationResponseMultiError is an error wrapping multiple
// validation errors returned by DeleteRegistrationResponse.ValidateAll() if
// the designated constraints aren't met.
type DeleteRegistrationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRegistrationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRegistrationResponseMultiError) AllErrors() []error { return m }

// DeleteRegistrationResponseValidationError is the validation error returned
// by DeleteRegistrationResponse.Validate if the designated constraints aren't met.
type DeleteRegistrationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRegistrationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRegistrationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRegistrationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRegistrationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRegistrationResponseValidationError) ErrorName() string {
	return "DeleteRegistrationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRegistrationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRegistrationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRegistrationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRegistrationResponseValidationError{}

// Validate checks the field values on ListRegistrationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRegistrationsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRegistrationsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRegistrationsRequestMultiError, or nil if none found.
func (m *ListRegistrationsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRegistrationsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := ListRegistrationsRequestValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListRegistrationsRequestMultiError(errors)
	}

	return nil
}

// ListRegistrationsRequestMultiError is an error wrapping multiple validation
// errors returned by ListRegistrationsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListRegistrationsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRegistrationsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRegistrationsRequestMultiError) AllErrors() []error { return m }

// ListRegistrationsRequestValidationError is the validation error returned by
// ListRegistrationsRequest.Validate if the designated constraints aren't met.
type ListRegistrationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRegistrationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRegistrationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRegistrationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRegistrationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRegistrationsRequestValidationError) ErrorName() string {
	return "ListRegistrationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRegistrationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRegistrationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRegistrationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRegistrationsRequestValidationError{}

// Validate checks the field values on ListRegistrationsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRegistrationsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRegistrationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRegistrationsResponseMultiError, or nil if none found.
func (m *ListRegistrationsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRegistrationsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetParticipants()) > 100 {
		err := ListRegistrationsResponseValidationError{
			field:  "Participants",
			reason: "value must contain no more than 100 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetParticipants() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRegistrationsResponseValidationError{
						field:  fmt.Sprintf("Participants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRegistrationsResponseValidationError{
						field:  fmt.Sprintf("Participants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRegistrationsResponseValidationError{
					field:  fmt.Sprintf("Participants[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListRegistrationsResponseMultiError(errors)
	}

	return nil
}

// ListRegistrationsResponseMultiError is an error wrapping multiple validation
// errors returned by ListRegistrationsResponse.ValidateAll() if the
// designated constraints aren't met.
type ListRegistrationsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRegistrationsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRegistrationsResponseMultiError) AllErrors() []error { return m }

// ListRegistrationsResponseValidationError is the validation error returned by
// ListRegistrationsResponse.Validate if the designated constraints aren't met.
type ListRegistrationsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRegistrationsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRegistrationsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRegistrationsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRegistrationsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRegistrationsResponseValidationError) ErrorName() string {
	return "ListRegistrationsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRegistrationsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRegistrationsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRegistrationsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRegistrationsResponseValidationError{}

// Validate checks the field values on Participant with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Participant) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Participant with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ParticipantMultiError, or
// nil if none found.
func (m *Participant) ValidateAll() error {
	return m.validate(true)
}

func (m *Participant) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ParticipantValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUsername()); l < 3 || l > 32 {
		err := ParticipantValidationError{
			field:  "Username",
			reason: "value length must be between 3 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ParticipantMultiError(errors)
	}

	return nil
}

// ParticipantMultiError is an error wrapping multiple validation errors
// returned by Participant.ValidateAll() if the designated constraints aren't met.
type ParticipantMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParticipantMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParticipantMultiError) AllErrors() []error { return m }

// ParticipantValidationError is the validation error returned by
// Participant.Validate if the designated constraints aren't met.
type ParticipantValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParticipantValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParticipantValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParticipantValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParticipantValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParticipantValidationError) ErrorName() string { return "ParticipantValidationError" }

// Error satisfies the builtin error interface
func (e ParticipantValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParticipant.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParticipantValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParticipantValidationError{}
